// Main entry point — explicit re-exports only (no `export *`).

export {
  armyCompositionByMode,
  armyCompositionInitiatives,
  armySchema,
  armySchemaForMode,
  refineArmyComposition,
  unitCountSchema,
  attackTypes,
  attackTypeSchema,
  coordinateSchema,
  boardSchema,
  boardSpaceSchema,
  boardType,
  boardTypeEnum,
  largeCoordinateLayout,
  smallCoordinateLayout,
} from '@entities';
export type { ArmyCompositionRules } from '@entities';
export {
  commandCardSchema,
  cardStateSchema,
  commandSchema,
  commandSizes,
  commandTypes,
  modifierSchema,
  restrictionsSchema,
  roundEffectSchema,
  standardCoordinateLayout,
  statModifiers,
  statModifierSchema,
} from '@entities';
export {
  engagementType,
  engagementTypeSchema,
  gameModes,
  gameModeNames,
  gameModeNameSchema,
  gameModeSchema,
  lineSchema,
} from '@entities';
export type { GameMode, GameModeName } from '@entities';
export { playerSchema, playerSides, playerSideSchema } from '@entities';
export {
  areSameSide,
  diagonalFacings,
  hasEngagedUnits,
  hasNoUnit,
  hasSingleUnit,
  orthogonalFacings,
  unitFacings,
} from '@entities';
export {
  engagedUnitPresenceSchema,
  noneUnitPresenceSchema,
  singleUnitPresenceSchema,
  unitFacingSchema,
  unitInstanceSchema,
  unitPlacementSchema,
  unitPresenceSchema,
  unitPresenceType,
  unitStatsSchema,
  unitStatNames,
  unitTypeSchema,
  unitWithPlacementSchema,
} from '@entities';
export {
  failValidationResultSchema,
  passValidationResultSchema,
  validationResultSchema,
} from '@utils';
export type {
  Army,
  AttackType,
  Board,
  BoardSpace,
  BoardType,
  CoordinateLayout,
  CoordinateLayoutMap,
  UnitCount,
} from '@entities';
export type {
  CommandCard,
  CardState,
  Command,
  CommandType,
  CommandSize,
  EngagementType,
  Modifier,
  Restrictions,
  RoundEffect,
  Coordinate,
  StatModifier,
  UnitSupport,
} from '@entities';
export type { Line, Player, PlayerSide, UnitFacing } from '@entities';
export type {
  EngagedUnitPresence,
  NoneUnitPresence,
  SingleUnitPresence,
  UnitInstance,
  UnitPlacement,
  UnitPresence,
  UnitPresenceType,
  UnitStatName,
  UnitStats,
  UnitType,
  UnitWithPlacement,
} from '@entities';
export type {
  FailValidationResult,
  PassValidationResult,
  ValidationResult,
} from '@utils';
export {
  ATTACK_RESOLUTION_CONTEXT_VALUES,
  attackResolutionContextSchema,
  COMPLETE_ATTACK_APPLY_EFFECT_TYPE,
  COMPLETE_CLEANUP_PHASE_EFFECT_TYPE,
  COMPLETE_ISSUE_COMMANDS_PHASE_EFFECT_TYPE,
  COMPLETE_MELEE_RESOLUTION_EFFECT_TYPE,
  COMPLETE_MOVE_COMMANDERS_PHASE_EFFECT_TYPE,
  eventSchema,
  eventTypes,
  eventTypeSchema,
  GAME_EFFECT_EVENT_TYPE,
  PLAYER_CHOICE_EVENT_TYPE,
} from '@events';
export {
  COMPLETE_PLAY_CARDS_PHASE_EFFECT_TYPE,
  COMPLETE_RANGED_ATTACK_COMMAND_EFFECT_TYPE,
  COMPLETE_RESOLVE_MELEE_PHASE_EFFECT_TYPE,
  COMPLETE_UNIT_MOVEMENT_EFFECT_TYPE,
  completeAttackApplyEventSchema,
  completeCleanupPhaseEventSchema,
  completeIssueCommandsPhaseEventSchema,
  completeMeleeResolutionEventSchema,
  completeMoveCommandersPhaseEventSchema,
  completePlayCardsPhaseEventSchema,
  completeRangedAttackCommandEventSchema,
  completeResolveMeleePhaseEventSchema,
} from '@events';
export {
  completeUnitMovementEventSchema,
  DISCARD_PLAYED_CARDS_EFFECT_TYPE,
  discardPlayedCardsEventSchema,
  gameEffectEventSchema,
  gameEffects,
  gameEffectTypeSchema,
  MELEE_ATTACK_RESOLUTION_CONTEXT,
  RALLY_ROUT_RESOLUTION_SOURCE,
  RANGED_ATTACK_RESOLUTION_CONTEXT,
  REAR_ENGAGEMENT_MOVEMENT_ROUT_SOURCE,
  RESOLVE_ENGAGE_RETREAT_OPTION_EFFECT_TYPE,
  RESOLVE_FLANK_ENGAGEMENT_EFFECT_TYPE,
} from '@events';
export {
  RESOLVE_INITIATIVE_EFFECT_TYPE,
  RESOLVE_MELEE_EFFECT_TYPE,
  RESOLVE_RALLY_EFFECT_TYPE,
  RESOLVE_RANGED_ATTACK_EFFECT_TYPE,
  RESOLVE_RETREAT_EFFECT_TYPE,
  RESOLVE_REVERSE_EFFECT_TYPE,
  RESOLVE_ROUT_EFFECT_TYPE,
  RESOLVE_UNITS_BROKEN_EFFECT_TYPE,
  resolveEngageRetreatOptionEventSchema,
  resolveFlankEngagementEventSchema,
  resolveInitiativeEventSchema,
  resolveMeleeEventSchema,
} from '@events';
export {
  resolveRallyEventSchema,
  resolveRangedAttackEventSchema,
  resolveRetreatEventSchema,
  resolveReverseEventSchema,
  resolveRoutEventSchema,
  resolveUnitsBrokenEventSchema,
  REVEAL_CARDS_EFFECT_TYPE,
  revealCardsEventSchema,
  ROUT_RESOLUTION_SOURCE_NON_ATTACK_VALUES,
  ROUT_RESOLUTION_SOURCE_VALUES,
  routResolutionSourceSchema,
  START_ENGAGEMENT_EFFECT_TYPE,
} from '@events';
export {
  chooseCardEventSchema,
  chooseMeleeResolutionEventSchema,
  chooseRallyEventSchema,
  chooseRetreatOptionEventSchema,
  chooseRoutDiscardEventSchema,
  chooseWhetherToRetreatEventSchema,
  startEngagementEventSchema,
  TRIGGER_ROUT_FROM_RETREAT_EFFECT_TYPE,
  triggerRoutFromRetreatEventSchema,
  triggerRoutFromRetreatMeleeSchema,
  triggerRoutFromRetreatRangedAttackSchema,
  triggerRoutFromRetreatSharedFieldsSchema,
} from '@events';
export {
  commitToMeleeEventSchema,
  commitToMovementEventSchema,
  commitToRangedAttackEventSchema,
  issueCommandEventSchema,
  moveCommanderEventSchema,
  moveUnitEventSchema,
  performRangedAttackEventSchema,
  playerChoiceEventSchema,
  playerChoiceTypeSchema,
  setupUnitsEventSchema,
} from '@events';
export type {
  AttackResolutionContext,
  CompleteAttackApplyEvent,
  CompleteCleanupPhaseEvent,
  CompleteIssueCommandsPhaseEvent,
  CompleteMeleeResolutionEvent,
  CompleteMoveCommandersPhaseEvent,
  CompletePlayCardsPhaseEvent,
  CompleteRangedAttackCommandEvent,
  CompleteResolveMeleePhaseEvent,
  CompleteUnitMovementEvent,
  DiscardPlayedCardsEvent,
  Event,
  EventType,
  GameEffectEvent,
} from '@events';
export type {
  GameEffectType,
  ResolveEngageRetreatOptionEvent,
  ResolveFlankEngagementEvent,
  ResolveInitiativeEvent,
  ResolveMeleeEvent,
  ResolveRallyEvent,
  ResolveRangedAttackEvent,
  ResolveRetreatEvent,
  ResolveReverseEvent,
  ResolveRoutEvent,
  ResolveUnitsBrokenEvent,
  RevealCardsEvent,
  RoutResolutionSource,
  RoutResolutionSourceNonAttack,
} from '@events';
export type {
  ChooseCardEvent,
  ChooseMeleeResolutionEvent,
  ChooseRallyEvent,
  ChooseRetreatOptionEvent,
  ChooseRoutDiscardEvent,
  ChooseWhetherToRetreatEvent,
  CommitToMeleeEvent,
  CommitToMovementEvent,
  CommitToRangedAttackEvent,
  IssueCommandEvent,
  MoveCommanderEvent,
  MoveUnitEvent,
  StartEngagementEvent,
  TriggerRoutFromRetreatEvent,
} from '@events';
export type {
  PerformRangedAttackEvent,
  PlayerChoiceEvent,
  PlayerChoiceType,
  SetupUnitsEvent,
} from '@events';
export {
  authoritativeGameSchema,
  blackSeenGameSchema,
  gameSchema,
  whiteSeenGameSchema,
} from '@game';
export type {
  CardStateForVisibility,
  Game,
  GameForVisibility,
  GameState,
  GameStateForVisibility,
  GameStateVisibility,
  OwnedPlayerForGameState,
  UnownedPlayerForGameState,
} from '@game';
export {
  attackResultSchema,
  CLEANUP_PHASE,
  cleanupPhaseStateSchema,
  cleanupPhaseSteps,
  commitmentSchema,
  completedCommitmentSchema,
  declinedCommitmentSchema,
  gameStateSchema,
  isAuthoritativeGameState,
  pendingCommitmentSchema,
} from '@game';
export {
  ISSUE_COMMANDS_PHASE,
  issueCommandsPhaseStateSchema,
  issueCommandsPhaseSteps,
  MOVE_COMMANDERS_PHASE,
  moveCommandersPhaseStateSchema,
  moveCommandersPhaseSteps,
  phases,
  phaseStateSchema,
  PLAY_CARDS_PHASE,
  playCardsPhaseStateSchema,
  playCardsPhaseSteps,
  RESOLVE_MELEE_PHASE,
} from '@game';
export {
  attackApplyStateSchema,
  commandResolutionStateSchema,
  engagementResolutionStateSchema,
  engagementStateSchema,
  flankEngagementResolutionStateSchema,
  frontEngagementResolutionStateSchema,
  meleeResolutionStateSchema,
  movementResolutionStateSchema,
  rallyResolutionStateSchema,
  resolveMeleePhaseStateSchema,
  resolveMeleePhaseSteps,
  roundStateSchema,
} from '@game';
export {
  rangedAttackResolutionStateSchema,
  rearEngagementResolutionStateSchema,
  retreatStateSchema,
  reverseStateSchema,
  routStateSchema,
} from '@game';
export type {
  AttackResult,
  Commitment,
  CompletedCommitment,
  DeclinedCommitment,
  PendingCommitment,
} from '@game';
export type {
  AttackApplyState,
  CleanupPhaseState,
  CleanupPhaseStep,
  IssueCommandsPhaseState,
  IssueCommandsPhaseStep,
  MoveCommandersPhaseState,
  MoveCommandersPhaseStep,
  Phase,
  PhaseState,
  PlayCardsPhaseState,
  PlayCardsPhaseStep,
  ResolveMeleePhaseState,
  ResolveMeleePhaseStep,
  RoundState,
} from '@game';
export type {
  CommandResolutionState,
  EngagementResolutionState,
  EngagementState,
  FlankEngagementResolutionState,
  FrontEngagementResolutionState,
  MeleeResolutionState,
  MovementResolutionState,
  RallyResolutionState,
  RangedAttackResolutionState,
  RearEngagementResolutionState,
  RetreatState,
  ReverseState,
  RoutState,
} from '@game';
export {
  applyAttackValue,
  getAdjacentSpaces,
  getBackSpaces,
  getBoardCoordinates,
  getBoardCoordinatesWithEngagedUnits,
  getBoardSpace,
  getDiagonallyAdjacentSpaces,
  getFlankingSpaces,
  getForwardSpace,
  getForwardSpacesToEdge,
  getInlineSpaces,
  getOrthogonallyAdjacentSpaces,
} from '@queries';
export {
  calculateInitiative,
  getFrontSpaces,
  getRearwardSpace,
  getSingleUnitWithPlacementAtCoordinate,
  getSpacesAhead,
  getSpacesBehind,
  getSpacesInArc,
  getSpacesInDirection,
  getSpacesWithinDistance,
  isEngagementFromFlank,
  isEngagementFromFront,
  isEngagementFromRear,
} from '@queries';
export {
  findMatchingCommand,
  getAdjacentFacings,
  getCurrentUnitStat,
  getLeftFacing,
  getLinesFromUnit,
  getMeleeSupportValue,
  getOppositeFacing,
  getOrthogonalFacings,
  getOtherPlayer,
  getOwnedPlayerCardState,
  getRightFacing,
  modifiersFromCompletedCommitment,
  getPlayerUnitsOnBoard,
  getPlayerUnitsWithPlacementOnBoard,
  getSupportedUnitTypes,
  getPlayerUnitWithPosition,
  hasUnitInSet,
  isFriendlyUnit,
  setWithoutUnit,
  areModifiersArraysEqual,
  areModifiersEqual,
  areRestrictionsEqual,
  isSameInstanceNumber,
  isSameUnitInstance,
  isSameUnitType,
} from '@queries';
export { getExpectedEvent } from '@expected';
export {
  canReverseUnit,
  findRetreatState,
  getAttackApplyStateFromMelee,
  getAttackApplyStateFromRangedAttack,
  getCleanupPhaseState,
  getCurrentCommandResolutionState,
  getCurrentPhaseState,
  getCurrentRallyResolutionState,
  getDefendingPlayerForNextIncompleteMeleeAttackApply,
  getEngagementStateFromMovement,
  getFlankEngagementStateFromMovement,
  getFrontEngagementStateFromMovement,
  getIssueCommandsPhaseState,
  getMeleeResolutionReadyForAttackCalculation,
  getMeleeResolutionState,
  getMoveCommandersPhaseState,
  getMovementResolutionState,
  getNextStepForResolveRally,
  getPlayCardsPhaseState,
  getRallyResolutionState,
  getRallyResolutionStateAwaitingBurn,
  getRallyResolutionStateAwaitingUnitsBroken,
  getRallyResolutionStateForCurrentStep,
  getRangedAttackResolutionState,
  getRearEngagementStateFromMovement,
  getResolveMeleePhaseState,
  getRetreatStateFromAttackApply,
  getRetreatStateFromMelee,
  getRetreatStateFromRangedAttack,
  getRetreatStateReadyForResolveFromMelee,
  getReverseStateFromAttackApply,
  getReverseStateFromMeleeResolutionByInitiative,
  getRoutStateFromAttackApply,
  getRoutStateFromCleanupPhaseForResolveRout,
  getRoutStateFromMeleeResolutionByInitiative,
  getRoutStateFromRally,
  getRoutStateFromRearEngagement,
} from '@queries';
export {
  checkDiagonalMove,
  getLegalChooseCardOptions,
  getLegalRetreats,
  getLegalUnitMoves,
} from '@legality';
export { getPositionOfUnit } from '@queries';
export type { Trait } from '@ruleValues';
export {
  COMMANDER_MOVE_DISTANCE,
  LEGAL_INITIATIVES,
  STANDARD_MAX_ARMY_UNIT_COST,
  MINI_MAX_ARMY_UNIT_COST,
  EPIC_MAX_ARMY_UNIT_COST,
  MAX_LINE_LENGTH,
  MIN_FLEXIBILITY_THRESHOLD,
  STANDARD_ARMY_CARDS_PER_INITIATIVE_COUNT,
  MINI_ARMY_CARDS_PER_INITIATIVE_COUNT,
  EPIC_ARMY_CARDS_PER_INITIATIVE_COUNT,
  STANDARD_MAX_ARMY_UNIT_TYPE_COUNT,
  MINI_MAX_ARMY_UNIT_TYPE_COUNT,
  EPIC_MAX_ARMY_UNIT_TYPE_COUNT,
  STANDARD_MIN_ARMY_MORALE_VALUE,
  MINI_MIN_ARMY_MORALE_VALUE,
  EPIC_MIN_ARMY_MORALE_VALUE,
  traits,
  traitSchema,
} from '@ruleValues';
export { tempCommandCards, tempUnits } from '@sampleValues';
export {
  addCommanderToBoard,
  addCommanderToLostCommanders,
  addCompletedPhase,
  addUnitsToCommandedUnits,
  addUnitToBoard,
  addUnitToRouted,
  burnCardFromPlayed,
  createEmptyGameState,
  createEmptyLargeBoard,
  createEmptySmallBoard,
  createEmptyStandardBoard,
  createUnitInstance,
} from '@transforms';
export {
  discardCardsFromHand,
  markPhaseAsComplete,
  moveBothInPlayToPlayed,
  moveCardToPlayed,
  removeCommanderFromBoard,
  removeUnitFromBoard,
  removeUnitFromReserve,
  replaceOwnedPlayerCardState,
  returnCardsToHand,
  revealBothAwaitingCards,
  revealCard,
  revealHiddenCard,
  updateAttackApplyState,
  updateBoardState,
  updateCommandResolutionState,
} from '@transforms';
export {
  updateCurrentInitiative,
  updateCurrentRoundNumber,
  updateHiddenPlayerCardState,
  updateMeleeAttackApplyState,
  updateMeleeResolutionState,
  updatePhaseState,
  updatePlayerCardState,
  updateRemainingPlayerCommands,
  updateRallyResolutionStateForCurrentStep,
  updateRetreatRoutState,
  updateRetreatState,
  updateReverseState,
  updateRoundState,
  updateRoutState,
} from '@transforms';
export { applyEvent } from '@transforms';
export {
  diagonalIsClear,
  hasEnemyUnit,
  isAtPlacement,
  isDefenseStat,
  isDiagonalFacing,
  isValidLine,
  matchesUnitRequirements,
} from '@queries';
export {
  eachCardPresentOnce,
  eachUnitPresentOnce,
  isLegalCardChoice,
  isLegalCommanderMove,
} from '@validation';
export {
  canEngageEnemy,
  canMoveInto,
  canMoveThrough,
  isLegalMove,
  isValidChooseCardEvent,
  isValidChooseRallyEvent,
  isValidChooseRoutDiscardEvent,
  isValidMoveCommanderEvent,
  validatePlayerChoice,
  validateEvent,
} from '@validation';
