import type { UnitType } from "./unitType.js";

export const tempUnits: UnitType[] = [
  {
    id: "1",
    name: "Swordsmen",
    traits: ["formation", "sword"],
    attack: 3,
    range: 0,
    speed: 2,
    flexibility: 2,
    reverse: 4,
    retreat: 3,
    rout: 5,
    cost: 15,
    limit: 8,
    routPenalty: 1,
  },
  {
    id: "2",
    name: "Spearmen",
    traits: ["formation", "spear", "phalanx"],
    attack: 3,
    range: 0,
    speed: 2,
    flexibility: 1,
    reverse: 4,
    retreat: 5,
    rout: 6,
    cost: 20,
    limit: 6,
    routPenalty: 2,
  },
  {
    id: "3",
    name: "Skirmishers",
    traits: ["skirmish", "javelin"],
    attack: 2,
    range: 1,
    speed: 3,
    flexibility: 3,
    reverse: 3,
    retreat: 3,
    rout: 3,
    cost: 8,
    limit: 6,
    routPenalty: 0,
  },
  {
    id: "4",
    name: "Cavalry",
    traits: ["mounted", "horse"],
    attack: 4,
    range: 0,
    speed: 4,
    flexibility: 3,
    reverse: 4,
    retreat: 4,
    rout: 5,
    cost: 25,
    limit: 2,
    routPenalty: 2,
  },
];
