export { gameEffects, type GameEffectType } from './gameEffectTypes';
export {
  COMMANDER_MOVE_DISTANCE,
  LEGAL_INITIATIVES,
  MAX_INITIATIVE_VALUE,
  MIN_INITIATIVE_VALUE,
  MAX_LINE_LENGTH,
  MIN_FLEXIBILITY_THRESHOLD,
  MAX_ARMY_UNIT_PER_TYPE_COUNT,
  STANDARD_ARMY_CARDS_PER_INITIATIVE_COUNT,
  STANDARD_MAX_ARMY_UNIT_TYPE_COUNT,
  STANDARD_MAX_ARMY_UNIT_COST,
  STANDARD_MIN_ARMY_MORALE_VALUE,
  MINI_ARMY_CARDS_PER_INITIATIVE_COUNT,
  MINI_MAX_ARMY_UNIT_TYPE_COUNT,
  MINI_MAX_ARMY_UNIT_COST,
  MINI_MIN_ARMY_MORALE_VALUE,
  EPIC_ARMY_CARDS_PER_INITIATIVE_COUNT,
  EPIC_MAX_ARMY_UNIT_TYPE_COUNT,
  EPIC_MAX_ARMY_UNIT_COST,
  EPIC_MIN_ARMY_MORALE_VALUE,
} from './ruleValues';
export { traits, traitSchema } from './traits';
export type { Trait } from './traits';
